# dependencies
  highlighter:      rouge
  kramdown:
    auto_ids:       true
  markdown:         kramdown

# permalinks
  permalink:        pretty

# server
  baseurl:          "/material" # workaround for our GitHub Pages hosting
  destination:      "gh-pages/material" # workaround for our GitHub Pages hosting
  encoding:         "UTF-8"
  exclude:          
                    - .git
                    - .gitignore
                    - .sass-cache
                    - assets/
                    - bower.json
                    - Gemfile
                    - Gemfile.lock
                    - gh-pages/
                    - Gruntfile.js
                    - lint-vars.sh
                    - node_modules/
                    - npm-shrinkwrap.json
                    - package.json
  host:             0.0.0.0
  plugins:
                    - jekyll-redirect-from
                    - jekyll-sitemap
                    - jekyll-toc
  port:             9999
  source:           "."
  url:              "http://daemonite.github.io/material"

# social
  authors:          "Daemonite"
  description:      "Daemonite's Material UI is a cross-platform and fully responsive front-end interface based on Google Material Design developed using Bootstrap 4."
  title:            "Material"

# vars
  cdn:
    jquery:         "https://code.jquery.com/jquery-3.2.1.slim.min.js"
    jquery_hash:    "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    md_font:        "https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i"
    md_icon:        "https://fonts.googleapis.com/icon?family=Material+Icons"
    popper:         "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"
    popper_hash:    "sha384-W1IgCZfiFCplncoIxD5rld+uzdB6FlcG2vm4qjrCP5Z7uUt7vnwbztJXeqXgd26w"
  current_version:  "4.0.0-beta"
  docs_version:     "4.0"
  download:
    source:         "https://github.com/Daemonite/material/archive/v4.0.0-beta.zip"
    dist:           "https://github.com/Daemonite/material/releases/download/v4.0.0-beta/material-4.0.0-beta-dist.zip"
  id:
    navbar:         "doc_navbar"
    navdrawer:      "doc_navdrawer"
  repo:             "https://github.com/Daemonite/material"
