# dependencies
  highlighter:      rouge
  kramdown:
    auto_ids:       true
  markdown:         kramdown

# permalinks
  permalink:        pretty

# plugins
  plugins:
                    - jekyll-redirect-from
                    - jekyll-sitemap
                    - jekyll-toc

# server
  baseurl:          "/material" # workaround for our GitHub Pages hosting
  destination:      "gh-pages/material" # workaround for our GitHub Pages hosting
  encoding:         "UTF-8"
  exclude:          
                    - .babelrc.js
                    - .eslintignore
                    - .git
                    - .gitignore
                    - .sass-cache/
                    - assets/
                    - bower.json
                    - build/
                    - docs-assets/
                    - Gemfile
                    - Gemfile.lock
                    - gh-pages/
                    - lint-vars.sh
                    - node_modules/
                    - package.json
                    - package-lock.json
                    - README.md
  host:             0.0.0.0
  port:             9999
  source:           "."
  url:              "http://daemonite.github.io/material"

# social
  authors:          "Daemonite"
  description:      "Daemonite's Material UI is a cross-platform and fully responsive front-end interface based on Google Material Design developed using Bootstrap 4."
  title:            "Material"

# vars
  cdn:
    bs_css:         "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    bs_css_docs:    "https://getbootstrap.com/assets/css/docs.min.css"
    bs_js:          "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    bs_js_docs:     "https://getbootstrap.com/assets/js/docs.min.js"
    jquery:         "https://code.jquery.com/jquery-3.3.1.slim.min.js"
    jquery_hash:    "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    md_font:        "https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i"
    md_icon:        "https://fonts.googleapis.com/icon?family=Material+Icons"
    popper:         "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    popper_hash:    "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  current_version:  "4.0.0"
  docs_version:     "4.0"
  download:
    source:         "https://github.com/Daemonite/material/archive/v4.0.0.zip"
    dist:           "https://github.com/Daemonite/material/releases/download/v4.0.0/material-4.0.0-dist.zip"
  id:
    navbar:         "doc-navbar"
    navdrawer:      "doc-navdrawer"
  repo:             "https://github.com/Daemonite/material"
